### ISSUE TITLE
create fibonacci in python

### ISSUE THREAD

**Issue by mithunayak-007** [ZED007-blip/hacktoberfest#12]

**Comment by theavitw** [comment]
assign me

**Comment by mithunayak-007** [comment]
assigned @theavitw

**Comment by theavitw** [comment]
hey @ZED007-blip 
I see that you didn't assing me,
Assignment is important for hacktoberfest

**Comment by mithunayak-007** [comment]
already assigned to you just work on

**Comment by theavitw** [comment]
Hey @ZED007-blip 
If you don't know there is an assignment option available.
And once you assign that project to anyone, there is an assigne portion in which one can found there name.
