### ISSUE TITLE
create a python file for prime number

### ISSUE THREAD

**Issue by mithunayak-007** [ZED007-blip/hacktoberfest#2]

**Comment by AmosBlack** [comment]
For checking prime numbers ? I believe I can do it, so please assign the issue to me.

**Comment by mithunayak-007** [comment]
assigned @AmosBlack

**Comment by AmosBlack** [comment]
Done! https://github.com/ZED007-blip/hacktoberfest/pull/20
Please assign hacktoberfest-accepted label to the PR as well 😄
